ARG registry
FROM ${registry}/hyacc/base:latest

ENV RAILS_ENV=test

ADD Gemfile Gemfile.lock ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle config unset without && \
    bundle install -j2

ADD Rakefile ./
ADD config ./config
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle exec rake dad:setup:test
