ARG build_number
ARG registry
FROM ${registry}/hyacc/base:${build_number}

ADD Gemfile Gemfile.lock Rakefile ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle config unset without && \
    bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    yarn install

ADD config/itamae ./config/
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle exec rake dad:setup:test
