version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [bundle, exec, rails, s, -b, 0.0.0.0]
    environment:
      MYSQL_HOST: mysql
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app/current
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hyacc_dev
      MYSQL_USER: hyacc
      MYSQL_PASSWORD: hyacc
