ARG build_number
ARG registry
FROM ${registry}/hyacc/base:${build_number}

ADD Gemfile Gemfile.lock Rakefile ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle config unset without && \
    bundle install -j2

ADD config ./config
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle exec rake dad:setup:test
