ARG registry
FROM ${registry}/hybitz-almalinux:8.10-20251117-44

RUN sudo yum -y install mariadb sqlite-devel

ADD Gemfile Gemfile.lock Rakefile ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle config unset without && \
    bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    yarn install
