apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyacc-app
  labels:
    app: hyacc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyacc-app
  template:
    metadata:
      labels:
        app: hyacc-app
    spec:
      restartPolicy: Always
      containers:
      - name: hyacc
        image: hyacc/app:latest
        envFrom:
        - configMapRef:
            name: hyacc-config
        - secretRef:
            name: hyacc-secret
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: PORT
          value: '3000'
        command: ['bundle', 'exec', 'rails', 's']
      - name: memcached
        image: memcached:1.4.39
        args: ['-m', '64']
