self:
  first_boot: true

current_user:
  mm/: admin?
  mm/careers: true

current_company:
  deemed_taxes: tax_simplified?
  financial_return_statements: '!personal?'
  payrolls: '!personal?'
  social_expenses: '!personal?'
  taxes: tax_exclusive?

  mm/employees: '!personal?'
  mm/inhabitant_taxes: '!personal?'
  mm/users:
    index: personal?

  mv/social_insurances: '!personal?'
  mv/withheld_taxes: '!personal?'

  report/withholding_slip: '!personal?'
