self:
  first_boot: true

current_company:
  debts: branch_mode
  deemed_taxes: tax_simplified?
  employees: '!personal?'
  financial_return_statements: '!personal?'
  houseworks: personal?
  housework_details: personal?
  inhabitant_taxes: '!personal?'
  payrolls: '!personal?'
  social_expenses: '!personal?'
  taxes: tax_exclusive?
  mv/social_insurances: '!personal?'
  mv/withheld_taxes: '!personal?'
  withholding_slip: '!personal?'
