default: &default
  adapter: mysql2
  encoding: utf8mb3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('MYSQL_PORT') { 3306 } %>
  username: <%= ENV.fetch('MYSQL_USER', 'hyacc') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'hyacc') %>

development:
  <<: *default
  database: hyacc_dev

test:
  <<: *default
  database: hyacc_test

production:
  <<: *default
  database: hyacc_pro
